const express = require('express');

const router = express.Router();

router.get('/', (req, res, next) => {
    res.json([
        {
            id: 0,
            title: 'Example One',
            content: 'Some text',
            creationDate: '2010-01-02',
            deadlineDate: '2020-12-28',
            importance: 0,
            finished: false,
            deleted: false,
        },
        {
            id: 1,
            title: 'Example Two',
            content: 'Some other text',
            creationDate: '2014-06-02',
            deadlineDate: '2015-12-23',
            importance: 1,
            finished: false,
            deleted: false,
        },
        {
            id: 2,
            title: 'Example Three',
            content: 'Some other text again',
            creationDate: '2012-06-02',
            deadlineDate: '2012-12-01',
            importance: 2,
            finished: false,
            deleted: false,
        },
        {
            id: 3,
            title: 'Example Four',
            content: 'Text again',
            creationDate: '2014-06-02',
            deadlineDate: '2028-10-01',
            importance: 3,
            finished: false,
            deleted: false,
        },
        {
            id: 4,
            title: 'Example Five',
            content: 'The again Text again',
            creationDate: '2009-06-02',
            deadlineDate: '2018-12-29',
            importance: 0,
            finished: false,
            deleted: false,
        },
        {
            id: 5,
            title: 'Example Six',
            content: 'Lorem ipsum',
            creationDate: '2001-06-02',
            deadlineDate: '2018-09-14',
            importance: 3,
            finished: true,
            deleted: false,
        },
        {
            id: 6,
            title: 'Example Seven',
            content: 'Lorem ipsum',
            creationDate: '2014-06-02',
            deadlineDate: '2018-09-14',
            importance: 2,
            finished: false,
            deleted: false,
        },
        {
            id: 7,
            title: 'Example Eight',
            content: 'Lorem ipsum',
            creationDate: '2014-06-02',
            deadlineDate: '2018-09-14',
            importance: 0,
            finished: false,
            deleted: false,
        },
        {
            id: 8,
            title: 'Example Nine',
            content: 'Lorem ipsum',
            creationDate: '2012-06-02',
            deadlineDate: '2018-09-14',
            importance: 3,
            finished: false,
            deleted: false,
        },
        {
            id: 9,
            title: 'Example Ten',
            content: 'Lorem ipsum',
            creationDate: '2012-11-02',
            deadlineDate: '2012-12-01',
            importance: 3,
            finished: false,
            deleted: false,
        },
        {
            id: 10,
            title: 'Example Eleven',
            content: 'Lorem ipsum',
            creationDate: '2012-11-02',
            deadlineDate: '2012-12-01',
            importance: 1,
            finished: false,
            deleted: false,
        },
        {
            id: 11,
            title: 'Example Twelve',
            content: 'Lorem ipsum',
            creationDate: '2012-11-02',
            deadlineDate: '2012-12-01',
            importance: 0,
            finished: false,
            deleted: false,
        },
        {
            id: 12,
            title: 'Example with an enormous amount of text. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
            content: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
            creationDate: '2018-06-14',
            deadlineDate: '2035-01-14',
            importance: 0,
            finished: false,
            deleted: false,
        },
    ]);
});

module.exports = router;
